version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - "8888:80"
    environment:
      - PYTHONPATH=/app  
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
